apiVersion: v1
entries:
  argo-cd:
  - annotations:
      category: Infrastructure
      images: |
        - name: argo-cd
          image: docker.io/bitnami/argo-cd:2.10.6-debian-12-r2
        - name: dex
          image: docker.io/bitnami/dex:2.39.1-debian-12-r0
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r18
        - name: redis
          image: docker.io/bitnami/redis:7.2.4-debian-12-r11
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.10.6
    created: "2024-09-02T18:13:44.877534+09:00"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 19.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Argo CD is a continuous delivery tool for Kubernetes based on GitOps.
    digest: ddc0051cacd6266b11b7a5dcfe28edf383bb66ba1c805b98c06cc1ebc56b93da
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/argo-cd/img/argo-cd-stack-220x234.png
    keywords:
    - Continuous delivery
    - Continuous deployment
    - Devops
    - Kubernetes
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: argo-cd
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/argo-cd
    urls:
    - argo-cd-6.0.9.tgz
    version: 6.0.9
  chartmuseum:
  - apiVersion: v2
    appVersion: 0.16.1
    created: "2024-09-02T18:13:44.878515+09:00"
    description: Host your own Helm Chart Repository
    digest: 972413e13343c5c193d1292fd92741550e8786eafef70091bd26c0310906aef3
    home: https://github.com/helm/chartmuseum
    icon: https://raw.githubusercontent.com/chartmuseum/charts/main/logo.jpg
    keywords:
    - chartmuseum
    - helm
    - charts repo
    maintainers:
    - name: chartmuseum
      url: https://github.com/chartmuseum
    name: chartmuseum
    sources:
    - https://github.com/chartmuseum/charts/tree/main/src/chartmuseum
    - https://github.com/chartmuseum
    - https://github.com/helm/chartmuseum
    urls:
    - chartmuseum-3.10.2.tgz
    version: 3.10.2
  harbor:
  - annotations:
      category: Infrastructure
      images: |
        - name: harbor-adapter-trivy
          image: docker.io/bitnami/harbor-adapter-trivy:2.9.1-debian-11-r0
        - name: harbor-core
          image: docker.io/bitnami/harbor-core:2.9.1-debian-11-r1
        - name: harbor-exporter
          image: docker.io/bitnami/harbor-exporter:2.9.1-debian-11-r1
        - name: harbor-jobservice
          image: docker.io/bitnami/harbor-jobservice:2.9.1-debian-11-r1
        - name: harbor-registry
          image: docker.io/bitnami/harbor-registry:2.9.1-debian-11-r1
        - name: harbor-registryctl
          image: docker.io/bitnami/harbor-registryctl:2.9.1-debian-11-r1
        - name: harbor-portal
          image: docker.io/bitnami/harbor-portal:2.9.1-debian-11-r0
        - name: nginx
          image: docker.io/bitnami/nginx:1.25.3-debian-11-r1
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r91
        - name: postgresql
          image: docker.io/bitnami/postgresql:13.13.0-debian-11-r0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.9.1
    created: "2024-09-02T18:13:44.888493+09:00"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 18.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 13.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Harbor is an open source trusted cloud-native registry to store,
      sign, and scan content. It adds functionalities like security, identity, and
      management to the open source Docker distribution.
    digest: c4ba080530802c0fa71171bffd76ade304374358d48fd887f0f03c5b7bb1ae1c
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/harbor-core/img/harbor-core-stack-220x234.png
    keywords:
    - docker
    - registry
    - vulnerability
    - scan
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: harbor
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/harbor
    urls:
    - harbor-19.1.1.tgz
    version: 19.1.1
  jenkins:
  - annotations:
      category: Infrastructure
      images: |
        - name: jenkins-agent
          image: docker.io/bitnami/jenkins-agent:0.3192.0-debian-11-r0
        - name: jenkins
          image: docker.io/bitnami/jenkins:2.414.3-debian-11-r1
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r90
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.414.3
    created: "2024-09-02T18:13:44.890396+09:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Jenkins is an open source Continuous Integration and Continuous Delivery
      (CI/CD) server designed to automate the building, testing, and deploying of
      any software project.
    digest: 151cf27c25dfc5d11b939759d7c93341b95de43ba7e20a024a047d581308ed5e
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/jenkins/img/jenkins-stack-220x234.png
    keywords:
    - jenkins
    - ci
    - cd
    - http
    - web
    - application
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: jenkins
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/jenkins
    urls:
    - jenkins-12.4.2.tgz
    version: 12.4.2
  nexus-repository-manager:
  - apiVersion: v2
    appVersion: 3.64.0
    created: "2024-09-02T18:13:44.891897+09:00"
    deprecated: true
    description: DEPRECATED Sonatype Nexus Repository Manager - Universal Binary repository
    digest: 7f8e43e9f868db71248fa10f4713e4c7ea0aa8c9edba93f1445710cb8b877ff5
    home: https://www.sonatype.com/nexus-repository-oss
    icon: https://sonatype.github.io/helm3-charts/NexusRepo_Vertical.svg
    keywords:
    - artifacts
    - dependency
    - management
    - sonatype
    - nexus
    - repository
    - quickstart
    - ci
    - repository-manager
    - nexus3
    name: nexus-repository-manager
    sources:
    - https://github.com/sonatype/nexus-public
    type: application
    urls:
    - nexus-repository-manager-64.2.0.tgz
    version: 64.2.0
  sonarqube:
  - annotations:
      category: DeveloperTools
      images: |
        - name: jmx-exporter
          image: docker.io/bitnami/jmx-exporter:0.20.0-debian-11-r0
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r90
        - name: sonarqube
          image: docker.io/bitnami/sonarqube:10.2.1-debian-11-r10
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 10.2.1
    created: "2024-09-02T18:13:44.896458+09:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 13.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: SonarQube(TM) is an open source quality management platform that
      analyzes and measures code's technical quality. It enables developers to detect
      code issues, vulnerabilities, and bugs in early stages.
    digest: 61537cdb9db1681eabecf3445ffade8582dec486e8b645ed98db2dd2d791fe82
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/sonarqube/img/sonarqube-stack-220x234.png
    keywords:
    - sonarqube
    - code-quality
    - code-review
    - static-analysis
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: sonarqube
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/sonarqube
    urls:
    - sonarqube-4.1.1.tgz
    version: 4.1.1
generated: "2024-09-02T18:13:44.867028+09:00"
