apiVersion: v1
entries:
  cassandra:
  - annotations:
      category: Database
      images: |
        - name: cassandra
          image: docker.io/bitnami/cassandra:4.1.4-debian-12-r4
        - name: cassandra-exporter
          image: docker.io/bitnami/cassandra-exporter:2.3.8-debian-12-r17
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r16
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 4.1.4
    created: "2024-09-02T18:13:00.375731+09:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache Cassandra is an open source distributed database management
      system designed to handle large amounts of data across many servers, providing
      high availability with no single point of failure.
    digest: b21b272eaf794ee8a2fc361dc0cdf498fb6e1e7db88b7b09f15148e52e76477e
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/cassandra/img/cassandra-stack-220x234.png
    keywords:
    - cassandra
    - database
    - nosql
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: cassandra
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/cassandra
    urls:
    - cassandra-10.12.1.tgz
    version: 10.12.1
  infisical-standalone:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-09-02T18:13:00.384203+09:00"
    dependencies:
    - condition: ingress.nginx.enabled
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: 4.0.13
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 14.1.3
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 18.14.0
    description: A helm chart for a full Infisical application
    digest: f72e74b092f7b186ff370a53f45100114e8fcb0b7a27420f379a105c0fcc278c
    name: infisical-standalone
    type: application
    urls:
    - infisical-standalone-1.0.8.tgz
    version: 1.0.8
  mariadb:
  - annotations:
      category: Database
      images: |
        - name: mariadb
          image: docker.io/bitnami/mariadb:11.2.3-debian-12-r4
        - name: mysqld-exporter
          image: docker.io/bitnami/mysqld-exporter:0.15.1-debian-12-r8
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r16
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 11.2.3
    created: "2024-09-02T18:13:00.386762+09:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MariaDB is an open source, community-developed SQL database server
      that is widely in use around the world due to its enterprise features, flexibility,
      and collaboration with leading tech firms.
    digest: 7034831663964829d77722694029a6074e8d4e5307cc8fc65a2f6afc4766175c
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: mariadb
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    urls:
    - mariadb-16.5.0.tgz
    version: 16.5.0
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r91
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.15.0-debian-11-r2
        - name: postgresql
          image: docker.io/bitnami/postgresql:16.1.0-debian-11-r15
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 16.1.0
    created: "2024-09-02T18:13:00.389307+09:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 6f92281c248236c33d676b08faa9a6ea995e0f890724d4eedc2ffe990d433b71
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - postgresql-13.2.23.tgz
    version: 13.2.23
  redis:
  - annotations:
      category: Database
      images: |
        - name: kubectl
          image: docker.io/bitnami/kubectl:1.29.2-debian-12-r3
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r16
        - name: redis
          image: docker.io/bitnami/redis:7.2.4-debian-12-r9
        - name: redis-exporter
          image: docker.io/bitnami/redis-exporter:1.58.0-debian-12-r4
        - name: redis-sentinel
          image: docker.io/bitnami/redis-sentinel:7.2.4-debian-12-r7
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 7.2.4
    created: "2024-09-02T18:13:00.391981+09:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: 6c71f072089256fd49cd9f09a19f098f1349ea3e9eee422c190c373e63ddd885
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - redis-19.0.1.tgz
    version: 19.0.1
generated: "2024-09-02T18:13:00.373556+09:00"
