apiVersion: v1
entries:
  tensorflow-resnet:
  - annotations:
      category: MachineLearning
      images: |
        - name: tensorflow-resnet
          image: docker.io/bitnami/tensorflow-resnet:2.14.0-debian-11-r0
        - name: tensorflow-serving
          image: docker.io/bitnami/tensorflow-serving:2.14.0-debian-11-r0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.14.0
    created: "2024-09-02T18:12:47.01671+09:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: TensorFlow ResNet is a client utility for use with TensorFlow Serving
      and ResNet models.
    digest: 3f35ce9e32707a4c4c10e894cfa86527a940857fffb4755279ef97370a0ce19f
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/tensorflow-inception/img/tensorflow-inception-stack-220x234.png
    keywords:
    - tensorflow
    - serving
    - resnet
    - machine
    - learning
    - library
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: tensorflow-resnet
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/tensorflow-resnet
    urls:
    - tensorflow-resnet-3.10.2.tgz
    version: 3.10.2
generated: "2024-09-02T18:12:47.014586+09:00"
