name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행
  pull_request:
    branches:
      - main  # main 브랜치에 대한 pull request가 있을 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run custom bash script
      run: |
        chmod +x ./your-script.sh  # 실행 권한 부여
        ./your-script.sh

    - name: Commit and Push changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Run custom script and update content"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Jekyll site using Docker
      run: |
        docker run --rm \
          -v "$PWD:/srv/jekyll" \
          -v "$PWD/vendor/bundle:/usr/local/bundle" \
          jekyll/jekyll:latest \
          jekyll build

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        cd _site
        git init
        git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy site to GitHub Pages"
        git push --force origin gh-pages
