name: Build and Deploy Jekyll Site

permissions:
  contents: write

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행
  pull_request:
    branches:
      - main  # main 브랜치에 대한 pull request가 있을 때 실행

jobs:
name: Update content

on:
  push:
    branches:
      - main

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "myeong-han"
        git config user.email "myeong-han@users.noreply.github.com"

    - name: Run custom script
      run: |
        chmod +x ./charts/generate-README.sh  # 실행 권한 부여
        ./charts/generate-README.sh

    - name: Commit changes
      run: |
        git add -A
        git commit -m "[Action/bot] Re-generate README.md"
    
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Build Jekyll site using Docker
      run: |
        docker run --rm \
          -v "$PWD:/srv/jekyll" \
          -v "$PWD/vendor/bundle:/usr/local/bundle" \
          jekyll/jekyll:latest \
          jekyll build

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        cd _site
        git init
        git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy site to GitHub Pages"
        git push --force origin gh-pages
