name: Build and Deploy Jekyll Site

permissions:
  contents: write

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행
  pull_request:
    branches:
      - main  # main 브랜치에 대한 pull request가 있을 때 실행

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "myeong-han"
        git config user.email "myeong-han@users.noreply.github.com"

    - name: Run custom script
      run: |
        chmod +x ./charts/generate-README.sh  # 실행 권한 부여
        ./charts/generate-README.sh

    - name: Commit changes
      run: |
        git add -A
        git commit -m "[Action/bot] Re-generate README.md" || echo "No changes to commit"
    
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
